name: Directory Listing

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: '.'  # Directory to generate index

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          path: 'public'  # Path to the generated directory listing